---
# tasks file for users

- name: Generate admin users
  become: yes
  user:
    name={{ item.name }}
    shell=/bin/bash
    comment="admin user"
    generate_ssh_key=yes
  with_items: "{{ users_admin | default([]) }}"
  tags: users

- name: Ensure admin users have root access
  become: yes
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ item.name }}' line='%{{ item.name }} ALL=(ALL) NOPASSWD: ALL'"
  with_items: "{{ users_admin | default([]) }}"
  tags: users

- name: Ensure admins have access to the server
  become: yes
  copy:
    content={{ item.pub_key }}
    dest=/home/{{ item.name }}/.ssh/authorized_keys
    owner={{ item.name }}
    group={{ item.name }}
    mode=0644
  with_items: "{{ users_admin | default([]) }}"
  tags: users

- name: Generate web users
  become: yes
  user:
    name={{ item.name }}
    shell=/bin/bash
    comment="web user"
    generate_ssh_key=yes
  with_items: "{{ users_web | default([]) }}"
  tags: users
